### ISSUE TITLE
Add a tour of Elm to htps://elmcraft.org/learn/

### ISSUE THREAD

**Issue by marc136** [axelerator/a-tour-of-elm#13]
Hello, I'm not sure if this is the right place to ask this, but I think it would be great if your tour of Elm would be listed at https://elmcraft.org/learn/

Would this be ok for you @axelerator?

Adding it would be as simple as editing https://github.com/elmcraft/elmcraft.org/edit/main/content/learn/index.md and creating a PR.

I don't want to pressure you, if you don't want to be listed there, or if you want to reach a goal first, I understand.

Thank you for taking the time to create the tour.

**Comment by axelerator** [comment]
Thanks for the pointer! Happy to have it added. I created a [PR](https://github.com/elmcraft/elmcraft.org/pull/31)
